# Generated by Django 5.1.15 on 2026-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID пользователя в Telegram для отправки уведомлений.",
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
