# Generated by Django 6.0.7 on 2026-08-02 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Например: 'Дом', 'Офис', 'Спортзал'.", max_length=255, verbose_name="Название места"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Опциональное описание места.", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если True, место видно другим пользователям.",
                        verbose_name="Публичное место",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Пользователь, создавший это место.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ["-created_at"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time",
                    models.TimeField(
                        help_text="Время суток, когда нужно выполнить привычку.", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Описание действия, например: 'я буду делать зарядку'.",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Если True, привычка является приятной (вознаграждением).",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Текстовое описание вознаграждения (не для приятных привычек).",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения в днях (от 1 до 7).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность (дней)",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        help_text="Предполагаемое время выполнения в секундах (макс. 120).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время на выполнение (сек)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если True, привычка видна другим пользователям.",
                        verbose_name="Публичная привычка",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая является вознаграждением (только для полезных привычек).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_as_reward",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Пользователь, создавший привычку.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Место выполнения привычки (необязательно).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.place",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
