# Generated by Django 6.0.7 on 2026-08-02 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "telegram_chat_id",
                    models.CharField(
                        help_text="Уникальный идентификатор чата пользователя в Telegram.",
                        max_length=64,
                        unique=True,
                        verbose_name="Telegram chat ID",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Username пользователя в Telegram (необязательно).",
                        max_length=255,
                        null=True,
                        verbose_name="Telegram username",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если False, уведомления этому пользователю не отправляются.",
                        verbose_name="Активная рассылка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания профиля Telegram.",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Пользователь, привязанный к этому Telegram-аккаунту.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram-профиль",
                "verbose_name_plural": "Telegram-профили",
                "ordering": ["-created_at"],
            },
        ),
    ]