# Generated by Django 6.0.7 on 2026-08-02 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramprofile",
            options={"verbose_name": "Telegram профиль", "verbose_name_plural": "Telegram профили"},
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="telegram_chat_id",
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="notified",
            field=models.BooleanField(default=True, verbose_name="Уведомления включены"),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="telegram_id",
            field=models.BigIntegerField(
                default=0, help_text="Telegram user ID", unique=True, verbose_name="Telegram ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Привязанный пользователь Sky Habit",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]