# Generated by Django 6.0.7 on 2026-08-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_alter_telegramprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Telegram-профиль",
                "verbose_name_plural": "Telegram-профили",
            },
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="notified",
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="telegram_id",
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Если False, уведомления этому пользователю не отправляются.",
                verbose_name="Активная рассылка",
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Уникальный идентификатор чата пользователя в Telegram.",
                null=True,
                unique=True,
                verbose_name="Telegram chat ID",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата и время создания профиля Telegram.", verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Username пользователя в Telegram (необязательно).",
                max_length=255,
                null=True,
                verbose_name="Telegram username",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Пользователь, привязанный к этому Telegram-аккаунту.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
